### PR TITLE
Remove deprecated OMIS public endpoints

### PR DESCRIPTION
**Pull request by elcct**
### Description of change

This removes all deprecated OMIS public endpoints that used OAuth2 authentication.

There is a separate commit for each app. 

It could be merged once OMIS frontend update has been released.

### Checklist

* [x] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [x] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

### CODE REVIEW

**Comment by reupen** [comment]
Are we able to remove the `public_omis_front_end` OAuth scope with this?

**Comment by elcct** [comment]
Definitely! I am going to raise a separate PR as this one is quite big.

**Comment by reupen** [comment]
@elcct I think a 'legacy' sneaked in here at some point:

https://github.com/uktrade/data-hub-api/blob/0bd9c37203f1d4833127390090e4ef3dfac38cb9/datahub/omis/payment/views.py#L76

**Comment by elcct** [comment]
OMIS update has been released, so this can be merged now.

**Pull request merged**
